name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Create PR with dist folder
        uses: googleapis/code-suggester@v4
        env:
          ACCESS_TOKEN: ${{ secrets.PAT }}
        with:
          command: pr
          upstream_repo: package-reputation-action
          upstream_owner: samdouble
          description: Build dist folder
          title: "chore: build dist"
          message: "chore: build dist"
          labels: automated pr
          branch: build-dist
          primary: master
          force: true
          git_dir: .
          fork: false

  release-please:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.PAT }}
          release-type: node
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
          target-branch: master
